/* eslint-disable prettier/prettier */
import { registerSheet } from 'react-native-actions-sheet';
import FundsBottomSheet from './FundsBottomSheet';
import SalesTypeSelectSheet from './SalesTypeSelectSheet';
import DescriptionSheet from './DescriptionSheet';
import ChannelSheet from './ChannelSheet';
import CustomerSheet from './CustomerSheet';
import DiscountSheet from './DiscountSheet';
import CartOptionsSheet from './CartOptionsSheet';
import DeliverySheet, { LocationSheet } from './DeliverySheet';
import VariantSheet from './VariantSheet';
import ReceiptPreviewSheet from './ReceiptPreview';
import AddProductSheet from './AddProductSheet';
import AddCategorySheet from './AddCategorySheet';
import EditProductSheet from './EditProductSheet';
import EditCategorySheet from './EditCategorySheet';
import CustomerDetailsSheet from './CustomerDetailsSheet';
import NotesSheet from './NotesSheet';
import OrderDateFilter from './OrderFilter';
import SelectedOrderSheet from './SelectedOrderSheet';
import ChangeOrderStatusSheet from './ChangeOrderStatusSheet';
import PayInternetSheet from './PayBillSheet';
import ConfirmBillPayment from './ConfirmBillPaymentSheet';
import BuyArtimeSheet from './BuyAirtimeSheet';
import ConfirmAirtimePayment from './ConfirmAirtimePaymentSheet';
import SendMoneySheet from './SendMoneySheet';
import ConfirmSendMoney from './ConfirmSendMoneySheet';
import DeliveryOptions from './DeliveryOptionsSheet';
import SummaryDateSheet from './DateFilter';
import TransferCommissionSheet from './TransferCommissionSheet';
import AddWalletSheet from './AddWalletSheet';
import AddMoneyAmount from './AddMoneyAmount';
import PaypointTransactions from './PaypointTransaction';
import SupportSheet from './SupportSheet';
import QuickSaleDiscount from './QuickSaleDiscount';
import AddProductVariants from './AddProductVariants';
import InventoryProductOptions from './InventoryProductOptions';
import PaypointTransactionFilter from './PaypointTransactionFilter';
import OutletSheet from './OutletSheet';
import TodoList from './TodoList';
import SalesHistoryFilter from './SalesHistoryFilter';
import SendMoneyFilter from './SendMoneyFilter';
import AirtimeFilterSheet from './AirtimeFilterSheet';
import BillFilter from './BillFilter';
import BuyInternetFilter from './BuyInternetFilter';
import TransferFilter from './TransferFilter';
import ScannedProduct from './ScannedProduct';
import InvoiceFilter from './InvoiceFilter';
import AnalyticsSheet from './AnalyticsSheet';
import DeliveryConfigure from './DeliveryConfigure';
import DeleteAccount from './DeleteAccount';
import AddBalance from './AddBalance';
import InventoryOutlet from './InventoryOutlets';
import ReceivedPayLater from './ReceivePayLater';
import DeliveryNote from './DeliveryNote';

registerSheet('add-funds', FundsBottomSheet);
registerSheet('sales-type', SalesTypeSelectSheet);
registerSheet('description', DescriptionSheet);
registerSheet('channels', ChannelSheet);
registerSheet('customers', CustomerSheet);
registerSheet('discount', DiscountSheet);
registerSheet('cartOptions', CartOptionsSheet);
registerSheet('delivery', DeliverySheet);
registerSheet('location', LocationSheet);
registerSheet('variants', VariantSheet);
registerSheet('receipt', ReceiptPreviewSheet);
registerSheet('addProduct', AddProductSheet);
registerSheet('addCategory', AddCategorySheet);
registerSheet('editProduct', EditProductSheet);
registerSheet('editCategory', EditCategorySheet);
registerSheet('customerDetails', CustomerDetailsSheet);
registerSheet('note', NotesSheet);
registerSheet('orderDate', OrderDateFilter);
registerSheet('selectedOrder', SelectedOrderSheet);
registerSheet('orderStatus', ChangeOrderStatusSheet);
registerSheet('payInternet', PayInternetSheet);
registerSheet('confirmBillPayment', ConfirmBillPayment);
registerSheet('buyAirtime', BuyArtimeSheet);
registerSheet('confirmAirtimePayment', ConfirmAirtimePayment);
registerSheet('sendMoney', SendMoneySheet);
registerSheet('confirmSendMoney', ConfirmSendMoney);
registerSheet('deliveryOptions', DeliveryOptions);
registerSheet('summaryFilter', SummaryDateSheet);
registerSheet('AnalyticsFilter', AnalyticsSheet);
registerSheet('transferCommission', TransferCommissionSheet);
registerSheet('addWallet', AddWalletSheet);
registerSheet('addMoneyAmount', AddMoneyAmount);
registerSheet('transaction', PaypointTransactions);
registerSheet('support', SupportSheet);
registerSheet('quickSaleDiscount', QuickSaleDiscount);
registerSheet('addProductVariants', AddProductVariants);
registerSheet('inventoryProductOptions', InventoryProductOptions);
registerSheet('paypointHistorySheet', PaypointTransactionFilter);
registerSheet('outlets', OutletSheet);
registerSheet('todoList', TodoList);
registerSheet('saleHistory', SalesHistoryFilter);
registerSheet('sendMoneyFilter', SendMoneyFilter);
registerSheet('AirtimeFilter', AirtimeFilterSheet);
registerSheet('BillFilter', BillFilter);
registerSheet('InternetFilter', BuyInternetFilter);
registerSheet('TransferFilter', TransferFilter);
registerSheet('ScannedProduct', ScannedProduct);
registerSheet('InvoiceFilter', InvoiceFilter);
registerSheet('Analytics', AnalyticsSheet);
registerSheet('Delivery Configure', DeliveryConfigure);
registerSheet('Delete Account', DeleteAccount);
registerSheet('Add Balance', AddBalance);
registerSheet('inventoryOutlet', InventoryOutlet);
registerSheet('Receive PayLater', ReceivedPayLater);
registerSheet('deliveryNote', DeliveryNote);
export {};

